### ISSUE TITLE
Testing packages fails with: Error: Cannot find module 'mocha-jsdom'

### ISSUE THREAD

**Issue by flippyhead** [DispatchMe/meteor-mocha-phantomjs#2]
I'm running `meteor test-packages --once --driver-package dispatch:mocha-hpantomjs` on a pretty simple package with some basic tests running on both client and server. Full error is:

```
=> Started MongoDB.                           
I20160408-10:03:57.022(-7)?                   
I20160408-10:03:57.023(-7)? --------------------------------
I20160408-10:03:57.024(-7)? ----- RUNNING SERVER TESTS -----
I20160408-10:03:57.024(-7)? --------------------------------
I20160408-10:03:57.024(-7)? 
I20160408-10:03:57.025(-7)? 
I20160408-10:03:57.025(-7)? 
I20160408-10:03:57.025(-7)?   0 passing (0ms)
I20160408-10:03:57.025(-7)? 
I20160408-10:03:57.025(-7)? 
I20160408-10:03:57.026(-7)? --------------------------------
I20160408-10:03:57.026(-7)? ----- RUNNING CLIENT TESTS -----
I20160408-10:03:57.026(-7)? --------------------------------
I20160408-10:03:57.026(-7)? 
=> Started your app.

=> App running at: http://localhost:3000/
I20160408-10:03:57.895(-7)? Error: Cannot find module 'mocha-jsdom'
I20160408-10:03:57.895(-7)? 
I20160408-10:03:57.895(-7)? 
I20160408-10:03:57.895(-7)?   phantomjs://code/phantomjsScript.js:15 in onError
I20160408-10:03:57.895(-7)?     http://localhost:3000/packages/modules-runtime.js?hash=939c79dfda40f1a849312e224b12b3aa11452782: 417
I20160408-10:03:57.896(-7)? 
I20160408-10:03:57.896(-7)?   phantomjs://code/phantomjsScript.js:17
I20160408-10:03:57.896(-7)?     http://localhost:3000/packages/modules-runtime.js?hash=939c79dfda40f1a849312e224b12b3aa11452782: 98
I20160408-10:03:57.896(-7)? 
I20160408-10:03:57.896(-7)?   phantomjs://code/phantomjsScript.js:17
I20160408-10:03:57.896(-7)?     http://localhost:3000/packages/local-test_pathable-ui.js?hash=0c90ca283fec2250910bae934cd6389fa6d31d47: 34
I20160408-10:03:57.896(-7)? 
I20160408-10:03:57.896(-7)?   phantomjs://code/phantomjsScript.js:17
I20160408-10:03:57.897(-7)?     http://localhost:3000/packages/modules-runtime.js?hash=939c79dfda40f1a849312e224b12b3aa11452782: 158
I20160408-10:03:57.897(-7)? 
I20160408-10:03:57.897(-7)?   phantomjs://code/phantomjsScript.js:17
I20160408-10:03:57.897(-7)?     http://localhost:3000/packages/modules-runtime.js?hash=939c79dfda40f1a849312e224b12b3aa11452782: 92
I20160408-10:03:57.897(-7)? 
I20160408-10:03:57.898(-7)?   phantomjs://code/phantomjsScript.js:17
I20160408-10:03:57.898(-7)?     http://localhost:3000/packages/local-test_pathable-ui.js?hash=0c90ca283fec2250910bae934cd6389fa6d31d47: 22831
I20160408-10:03:57.898(-7)? 
I20160408-10:03:57.898(-7)?   phantomjs://code/phantomjsScript.js:17
I20160408-10:03:57.898(-7)? 
I20160408-10:03:57.914(-7)? %s%s  
I20160408-10:03:57.914(-7)? 
I20160408-10:03:57.914(-7)? %s%s    Profile class
I20160408-10:03:57.914(-7)? 
I20160408-10:03:57.914(-7)? %s%s      a valid Profile
I20160408-10:03:57.914(-7)? %s%s        full name
I20160408-10:03:57.915(-7)? 
I20160408-10:03:57.932(-7)? MochaRunner.runServerTests: Starting server side tests with run id 2FM5uwYvCrhp7fFd6
W20160408-10:03:58.048(-7)? (STDERR) MochaRunner.runServerTests: failures: 0
I20160408-10:04:27.986(-7)? All client and server tests finished!
I20160408-10:04:27.986(-7)? 
I20160408-10:04:27.986(-7)? --------------------------------
I20160408-10:04:27.986(-7)? SERVER FAILURES: 0
I20160408-10:04:27.986(-7)? CLIENT FAILURES: 2
I20160408-10:04:27.987(-7)? --------------------------------
```

Thank you!

**Comment by aldeed** [comment]
`npm i --save-dev mocha-jsdom` should fix it, but I'm not sure what the cause is without seeing the app or a simple app that reproduces the issue.

**Comment by flippyhead** [comment]
Thank you. I tried that but that doesn't fix the issue. 

t've created a simple repo that reproduces the error here: https://github.com/flippyhead/jsdom-error

Just run: `meteor test-packages --once --driver-package dispatch:mocha-hpantomjs` to see the above error.

**Comment by aldeed** [comment]
@flippyhead The repro app works if you make the following changes:

1. Replace `api.use(practicalmeteor:mocha)` with `api.use('dispatch:mocha-phantomjs');` in `package.js`. `practicalmeteor:mocha` conflicts with `mocha-phantomjs`.
2. Add `api.use('practicalmeteor:chai');` in `package.js` since your tests depend on it.
3. Add `./` at the end of your test command, making it `meteor test-packages --once --driver-package dispatch:mocha-phantomjs ./`

**Comment by flippyhead** [comment]
OK thank you, that does it.

I was hoping to have the ability to switch between a setup for our CI and one for local development -- the browser based specs being easier to work with in the latter. I guess we'll just comment out lines as needed.

Thanks so much for your help!

**Comment by aldeed** [comment]
You can add and use https://github.com/DispatchMe/meteor-mocha-browser for local in-browser.
